project:
  type: website

website:
  title: "Assignment-3-jao95"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: william.qmd
        text: William's Corner

format:
  html:
    theme:
      light: flatly
      dark: cyborg
    css: styles.css
    toc: true



